"use client";
import { useAuth } from "@/app/components/AuthContext";
import { redirect } from "next/navigation";
// import type { Metadata } from "next";
import { FormEvent, useState } from "react";

// export const metadata: Metadata = {
//     title: "Login",
//     description: "Generated by create next app",
// };


export default function Page()
{
    const [username, setUsername] = useState("");
    const { login } = useAuth();
    function onSubmit(e: FormEvent<HTMLFormElement>)
    {
        e.preventDefault();
        login(username);
        redirect("/");
    }

    return (
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <form className="card-body" onSubmit={onSubmit}>
                <div className="form-control">
                    <label className="label">
                        <span className="label-text">Username</span>
                    </label>
                    <input type="username"
                        placeholder="username"
                        className="input input-bordered"
                        required
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                    />
                </div>
                <div className="form-control mt-6">
                    <button className="btn btn-primary" type="submit">Login</button>
                </div>
            </form>
        </main>
    );
}
